### ISSUE TITLE
mongodb-native driver updated to 2.0.x

### ISSUE THREAD

**Issue by k-sheth** [jedireza/hapi-mongo-models#11]
mongo driver updated to 2.0.x. Is there a plan to update your dependencies ? Appreciate if you can do so earlier rather than later.

thx

**Comment by jedireza** [comment]
Sounds good. We'll do this soon.

**Comment by k-sheth** [comment]
Going through the mongo docs, the key changes are that insert, remove, update are deprecated, and insertOne, insertMany, removeOne, removeMany, updateOne are the preferred ways now.

**Comment by jedireza** [comment]
Closing this issue. Please come help out with PR #12

**Comment by k-sheth** [comment]
Am a bit busy through the week, I will go through the update-deps branch and report back by Sun.
