### ISSUE TITLE
max insert set to 1000

### ISSUE THREAD

**Issue by chacliff** [jedireza/hapi-mongo-models#13]
I'm not sure if this was something you did when you made the hapi-mongo-models but you cannot insert more than 1000 length array of documents into a mongo db with your calls. I also wanted to make you aware that this plugin is running on an extremely old version of mongodb version 1.4 i believe and the current version is 2.0.25. This might be the root of the issue.

**Comment by chacliff** [comment]
i might have to recant this issue being part of the mongodb version. your package.json file has peerdependencies set to ^2.x.x but for some reason the npm isn't updating my mongodb dependenciesi n my project.

**Comment by chacliff** [comment]
sorry that was just weird, i had to uninstall and reinstall the plugin to get it to update. i'm going to see if it changes the 1000 batch size limitation real quick. If it still comes up i'll leave the issue open

**Comment by chacliff** [comment]
I am still having an issue but its not the 1000 maximum limitation. It seems to work fine with my breaking up of the data. I am also intermixing mongoose and hapi-mongo-models. so until i exclusively make a standalone  to do one or the other i can't be sure that their mixing is causing an issue or not. For more information i'm inputting 91737 documents into the database all at once and it worked fine on my mongoose standalone app. 
I am closing the issue but your input would be appreciated. 
     `   rl.on('close', function() { `
`                   var chunk = []`
`			var iterations = 0; `
`			for( doc in objArray){`
`				chunk.push(objArray[doc]); `
`				if(chunk.length == 1000){`
`					db.collection.insert(chunk, function(err, result) {`
`						if(err) {`
`							console.log("Error: " + JSON.stringify(err));` 
`							reply({ 'ok': false, 'err': err });`					
`						}`
`					});`
`					chunk.length = 0;` 
`					iterations++;` 
`				}`
`			}`
`			if( chunk.length > 0){`
`				db.collection.insert(chunk, function(err, result) {`
`						if(err) {`
`							console.log("Error: " + JSON.stringify(err));` 
`							reply({ 'ok': false, 'err': err });`					
`						}`
`					});`
`			}`
`			console.log(iterations);` 
`			objArray.length = 0;`
`			console.log("save complete");` 
`			reply({ 'ok': true });`
 `       });`

**Comment by jedireza** [comment]
Thanks for opening an issue. I'll try to look at this when I get more time. Let's keep the issue open if you'd like others to confirm your results and/or give feedback.

**Comment by jedireza** [comment]
I haven't had a chance to look at this yet. Any new findings on your end?

**Comment by chacliff** [comment]
I had some time constraints on the project i was working on and ended up just creating a for loop to send the data across in batches, and ignore the issue. I should have some time to look at it this weekend.
