### ISSUE TITLE
Add distinct method

### ISSUE THREAD

**Issue by dscaramellino** [jedireza/hapi-mongo-models#18]
Hi, I was wondering if you had plans to add a .distinct method, which is available in mongodb's native driver.  Thanks!

**Comment by jedireza** [comment]
Thanks for creating an issue. Adding a `distinct` method sounds good to me.

**Comment by jedireza** [comment]
@dscaramellino `distinct` landed today. :tada:

**Comment by dscaramellino** [comment]
Awesome! Thanks so much!


*Danielle Scaramellino *Systems Developer

320 West 13th Street
New York, NY 10014

Dir      646 486 8179
Cell    845 222 7353
www.newvisions.org

facebook <https://www.facebook.com/newvisionsforpublicschools>   •  twitter
<https://twitter.com/NewVisionsNYC>
