### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by zephrax** [jedireza/hapi-mongo-models#21]
Hi, I want to use native aggregation methods of the mongodb library, but I can't find the way to use it through hapi-mongo-models.

Is there a way to do that?

**Comment by zephrax** [comment]
I found a way using the server-exposed BaseModel.

**Comment by jedireza** [comment]
Thanks for opening an issue. You are correct `BaseModel.db` is the raw MongoDB client.

The aggregations methods that can be tied to collections may be good candidates to expose through the models. For example see #15.
