### ISSUE TITLE
Cannot read property 'collection' of undefined

### ISSUE THREAD

**Issue by jameskolce** [jedireza/hapi-mongo-models#22]
Hi, I'm trying to test with Lab an API that uses `hapi-mongo-models` but I'm having an error:

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'collection' of undefined
    at Function.BaseModel.insertOne (/home/james/.../node_modules/hapi-mongo-models/lib/base-model.js:423:34)
    at Function.Endpoint.create (/home/james/.../models/endpoint.js:32:92)
    at server.route.handler (/home/james/.../server.js:134:90)
    at Object.internals.handler (/home/james/.../node_modules/hapi/lib/handler.js:94:36)
    at /home/james/.../node_modules/hapi/lib/handler.js:28:23
    at internals.Protect.run (/home/james/.../node_modules/hapi/lib/protect.js:56:5)
    at exports.execute (/home/james/.../node_modules/hapi/lib/handler.js:22:22)
    at /home/james/.../node_modules/hapi/lib/request.js:371:13
    at iterate (/home/james/.../node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/home/james/.../node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at /home/james/.../node_modules/hapi/node_modules/hoek/lib/index.js:841:22
    at process._tickDomainCallback (node.js:381:11)
```

**Test file:**

```JS
var Lab = require('lab');
var Code = require('code');
var server = require("../");

var lab = exports.lab = Lab.script();
var expect = Code.expect;


lab.experiment("Endpoint", function() {
  lab.test("creation", function(done) {
    var options = {
      method: "POST",
      url: "/api",
      payload: {
        email: 'test@test.com'
      }
    };

    server.inject(options, function(response) {
      var result = response.result;

      expect(response.statusCode).to.equal(200);
      expect(result).to.be.an.object();

      done();
    });
  });
});

```

**server.js**

```JS
...

handler: function (request, reply) {
    var Endpoint = request.server.plugins['hapi-mongo-models'].Endpoint;
    var data = request.payload;

    Endpoint.create(data, function (err, res) {

      if (err) {
        return reply(err);
      }

      reply(res[0]);
    });
  }

...
```

**models/endpoint.js**

```JS
...

Endpoint.create = function (data, callback) {
  data.date = new Date();

  this.insertOne(data, callback);
};

...
```

The error says that there is no ``collection`` property because ``BaseModel.db`` is undefined in:

```JS
BaseModel.insertOne = function () {
...

    var collection = BaseModel.db.collection(this._collection);

...
};
```

So I think I need to connect to the database first but I'm not sure about how to do it. Do you have any suggestions?

Thanks!

**Comment by jedireza** [comment]
Thanks for opening an issue.

How are you initiating `hapi-mongo-models`? You can see in Frame we use a manifest: https://github.com/jedireza/frame/blob/master/manifest.js#L33-L45

When `hapi-mongo-models` get's plugged in, it connects to the database for you. Did you pass the plugin MongoDB credentials?

**Comment by jameskolce** [comment]
Thanks for the reply.

I'm initiating `hapi-mongo-models` like this:

**server.js**
```JS
...

var HapiMongoModels = require('hapi-mongo-models');

...

server.register({
  register: HapiMongoModels,
  options: {
    mongodb: {
      url: 'mongodb://localhost:27017/project',
      options: {}
    },
    autoIndex: false,
    models: {
      Endpoint: './models/endpoint'
    }
  }
}, function (err) {

     if (err) {
         console.log('Failed loading HapiMongoModels');
     }
});
```

In my project everything works fine when I start the server, so I think the problem in just in the test file, because I get this error only when I run Lab. But I'm not sure, should I use a manifest instead?

**Comment by jedireza** [comment]
Ah. With Frame I actually create a fresh server before each test. You'll also notice how we pass in only the plugins that are needed. That may be an important difference to note.

https://github.com/jedireza/frame/blob/master/test/server/api/login.js#L22-L51

**Comment by jameskolce** [comment]
I included some `console.log()`s in `base-model.js` to test some things and seems like `BaseModel.connect` is never executed, so `BaseModel.db` is undefined inside of `BaseModel.insertOne`.

Maybe I need to initiate `hapi-mongo-models` in the test file before executing any tests, right?

Question about Frame: Why did you make it in that way?

**Comment by jedireza** [comment]
Without seeing the full `server.js` file of yours it's hard to tell. How is your server being started? Is the test running before the server starts?

**Comment by jedireza** [comment]
> Question about Frame: Why did you make it in that way?

Everything is a plugin. Which IIRC is the recommended way to compose larger hapi apps.

**Comment by jameskolce** [comment]
I was looking at Frame and now everything starts to make sense for me.

I'm going to move everything to plugins so I can create a fresh server before each test as you did with your project, I don't know where the problem could be but with this it should work.

Thanks!
