### ISSUE TITLE
find (Many)

### ISSUE THREAD

**Issue by Miscellaneous** [jedireza/hapi-mongo-models#24]
The following query does always return an empty array

Model.find( {  '_id': { $in: [ '4ed3ede8844f0f351100000c', '4ed3f117a844e0471100000d' ] }} );

**Comment by Miscellaneous** [comment]
Workaround: By processing all IDs (strings) in the _id array with ObjectId( id )

**Comment by jedireza** [comment]
Thanks for opening an issue. Your workaround does seem like it makes sense as the `_id` field is typed. I do wonder though, was an error was returned originally?

**Comment by Miscellaneous** [comment]
no errors, just empty array.

**Comment by jedireza** [comment]
I see. I would consider this expected behavior. Closing for now.
