### ISSUE TITLE
Model.insertOne() - returns array

### ISSUE THREAD

**Issue by Miscellaneous** [jedireza/hapi-mongo-models#25]
Seems to me, like Model.insertOne() will return an array with 1 object, instead of just the object.

**Comment by jedireza** [comment]
Thanks for opening an issue. Do you mean it should return an array or that it does and the docs are wrong?

**Comment by Miscellaneous** [comment]
I would imagine, .insertOne would return an object (without an nesting array).

I get (nested inside an array]:
result = [ {foo:1} ]

expected
result = {foo:1}

I base this upon .findOne() or .findById does indeed only return an object (without the nesting array).

**Comment by jedireza** [comment]
Ah yes, I remember this. We're simply proxying the call to the drivers `insertOne` method:
https://github.com/jedireza/hapi-mongo-models/blob/11fa7a6b270bfb04c75d31eb8ac86f283da336d5/lib/base-model.js#L439

According to the docs:
http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#insertOne

`insertOne` has a `writeOpCallback` callback:
http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#~writeOpCallback

Which defines the result as a `WriteOpResult`
http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#~WriteOpResult

If we chose to change this, it would be a major version bump as the API would change. Is it really worth it?

**Comment by Miscellaneous** [comment]
I'm new to Mongo, so not really in any position to advise on what is worth it. 

I just believed to have discovered an Inconsistency error, but being an artifact from the driver, it might be outside your domain.

Appreciate your framework and your kind support, I hope its not to much trouble too ask.

**Comment by jedireza** [comment]
> I just believed to have discovered an Inconsistency error, but being an artifact from the driver, it might be outside your domain.

We could change it in this library, but I prefer to do as little as possible in that regard.

> Appreciate your framework and your kind support, I hope its not to much trouble too ask.

That's always nice to hear. Thanks :) Always feel free to ask questions.

**Comment by Miscellaneous** [comment]
Model.insertOne() - Workaround to output object instead of array 

                            Model.insertOne( schema, function( err, model ){
                                if( err ) return reply( err );
                                model = model.shift();
                                return reply( model );
                            });
