### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by simon-p-r** [jedireza/hapi-mongo-models#26]
Hi

Where does the joi validation occur?  I can see the function created in base model class but can't see where it is used?

Thanks
Simon

**Comment by simon-p-r** [comment]
Sorry for the noise just found it in docs, my understanding is you call it yourself as joi returns the object if validated successfully which you can then use to update or insert into mongo.

**Comment by jedireza** [comment]
Thanks for opening an issue. And yes, validation is not used automatically, you do call it yourself.
