### ISSUE TITLE
ensureIndexes question

### ISSUE THREAD

**Issue by simon-p-r** [jedireza/hapi-mongo-models#28]
Hi again

Just wanted to know where the callback is for this method

https://github.com/jedireza/hapi-mongo-models/blob/436b6175d5e8a0ab63750b4647e7a6ff6ae4e3b3/index.js#L42

Docs says it should take a callback but here isn't one here unless I am missing something?

Thanks
Simon

**Comment by jedireza** [comment]
Thanks again for opening an issue. We should probably update the docs and note that callback as optional.

https://github.com/jedireza/hapi-mongo-models/blob/436b6175d5e8a0ab63750b4647e7a6ff6ae4e3b3/lib/base-model.js#L37

And in the case of the `Async.parallel()` call, it's callback is also optional.

https://github.com/caolan/async#paralleltasks-callback

**Comment by simon-p-r** [comment]
I have done a PR with commit fb8ec4ed0b69fffdcb5b6394cf902f734cb24b41 that should close this.
