### ISSUE TITLE
required() doesn't seem to work...

### ISSUE THREAD

**Issue by kynwu** [jedireza/hapi-mongo-models#33]
I got below document schema. However, I can still insert document without some keys....
shouldn't that the required property declare some field that cannot be ignore?
or do I misuse the Joi class? 

PrimaryAccount.schema = Joi.object().keys({ // token type
  _id: Joi.object(),
  type: Joi.string().required(),
  credit_card: Joi.object().keys({
    type: Joi.string().required(),
    cardholder_name: Joi.string().required(),
    card_number: Joi.string().creditCard().required(),
    exp_date: Joi.date().format('MMYY'),
    cvv: Joi.string().required()
  }),
  token: Joi.object().keys({
    value: Joi.string().required(),
    exp_date: Joi.date().format('MMYY').required()
  })
}).required();

**Comment by jedireza** [comment]
Thanks for opening an issue. Like I answered in the other thread...

- - - - -

`hapi-mongo-models` doesn't auto validate against the schema. It's up to you to call one of the `validate` functions and handle the result as you see fit.

 - https://github.com/jedireza/hapi-mongo-models/issues/33
 - https://github.com/jedireza/hapi-mongo-models#validatecallback

**Comment by kynwu** [comment]
I just saw it ! thanks for advising!
