### ISSUE TITLE
$set not recognized by updateOne()?

### ISSUE THREAD

**Issue by Chris0lsen** [jedireza/hapi-mongo-models#34]
I'm working on an application that uses hapi-mongo-models for its CRUD operations, and I want to update a document with some nested subdocuments. In vanilla Mongo I'd query by _id to find the doc I want to update, and pass a {$set:{}} object as my update, but for some reason I can't get it to update my document (doesn't return as error, just resolves without performing any updates). The same query runs properly in a mongo shell environment.

Is $set not supported by hapi-mongo-models?

Thanks!
Chris

**Comment by jedireza** [comment]
Thanks for opening an issue. This sounds strange and I'd expect a `{ $set: {} }` operation to behave as you described it should. Would you be willing to create a falling test or reproducible example?

**Comment by Chris0lsen** [comment]
I'll try to reproduce the error locally today at work, thanks for getting back to me!

**Comment by Chris0lsen** [comment]
Okay, I was able to reproduce the bug. It's not throwing an error (either in the callback or in the node console window. 

If you'd like i can give you the .js files I'm using to replicate the issue (there are only 3), but here's the route itself:

```javascript
{
		path: '/test',
		method: 'PUT',
		config: {
		validate: {
				payload: {
					_id: Joi.string().required(),
					Name: Joi.string(),
					TestSub: Joi.object().required()
				}
			}
		},
		handler: function(request, reply) {
			var Test = request.server.plugins['hapi-mongo-models']['Test'];
			var oid = request.payload._id;
			Test.findById(oid, function (err, results){
				if (err){
					response.error = err;
				}else {
					var incoming = request.payload.TestSub;
					var existing = results.TestSub;
					var response = {};
					for(var test in incoming){
						if(_.contains(Object.keys(existing), test)){
							for (var letter in incoming[test]){
								if(_.contains(results.TestArray, letter)){									
									var setModifier = { $set: {} };
									setModifier.$set['TestSub.' + test + '.' + letter + '.foo'] = incoming[test][letter].foo || results.TestSub[test][letter].foo || "";
									setModifier.$set['TestSub.' + test + '.' + letter + '.hello'] = incoming[test][letter].hello || results.TestSub[test][letter].hello || "";	
									Test.updateOne(
										{_id: oid},
										setModifier,
										{returnOriginal: false},
										function (err, docUpdated) {
											if(!err){
												response.data = docUpdated;
											} else {
												response.error = err;
											}
										}	
									);
								} 
							}
						} 
					}
				}
				reply(response);
			});
		}
	},
```
And here's Test.create() in my model:
```javascript
Test.create = function(Name, TestSub, TestArray, callback) {
	var doc = {
		Name: Name,
		TestSub: TestSub,
		TestArray: TestArray
	};
	this.insertOne(doc, function (err, Test) {
		if (err) {
			return callback(err);
		}
		callback(err, Test);
	});
};
```
If anything pops out to you, please let me know what I'm doing wrong! I'm happy to share the rest of the code I'm using in this test case too.

**Comment by Chris0lsen** [comment]
Here's the complementary query that works in Mongo shell, using the same dot notation produced by the code:
```javascript
db.test.update({"_id":ObjectId("56213317c695fb8011ba80e7")},{$set:{"TestSub.1.A.foo": "baz" }},{});
```

**Comment by Chris0lsen** [comment]
Seems to work with the native MongoClient too, I might be overlooking something in my code (it's admittedly convoluted):

```javascript
{
		path: '/test2',
		method: 'POST',
		handler: function(request, reply) {
			var oid = request.payload._id;
			var setModifier = { $set: {}};
			setModifier.$set['TestSub.1.A.foo'] = "baz";
			MongoClient.connect('mongodb://localhost:27017/test', function (err,db) {
				var collection = db.collection('test');
				collection.updateOne({_id:oid},setModifier);
			});
			reply("done");
		}
	}
```

**Comment by jedireza** [comment]
I created an example test case that demonstrates using the `$set` operator.

https://github.com/jedireza/hapi-mongo-models/blob/sanity-check-issue-34/test/lib/base-model.js#L1445-L1482

I don't think I'll merge this though. I wouldn't expect the need for these kinds of sanity checks in our test suite since we're just passing things along to the native driver anyway.

If I miss understood something in the issue, the best thing to do is create a test case demonstrating the issue in it's simplest form.
