### ISSUE TITLE
Request payload validation

### ISSUE THREAD

**Issue by prashaantt** [jedireza/hapi-mongo-models#40]
Instead of explicitly calling `validate` inside the handler itself, do you approve of something like this to validate the payload to a `Kitten` handler:

```javascript
server.route({
    method: 'POST',
    path: '/kittens',
    config: {
        validate: {
            payload: Kitten.schema
        }
    },
    handler: function (request, reply) {

        Kitten.create(request.payload, function (err, kitten) {

            if (err) {
                return reply(err);
            }

            reply(kitten);
        });
    }
});
```

I have a feeling I'm bringing up something very obvious and silly, but I haven't seen this pattern in the examples (yet). This may be a nice way to validate without repetition and returns useful error codes at the route level itself, if you won't be doing much else inside `Kitten.validate()`.

**Comment by jedireza** [comment]
Thanks for opening an issue.

Using the model schema in the route config is a creative solution and if it works for your needs then that's great.

There aren't any strict rules for this stuff. I don't use the `validate` much at all, I typically use the model schema so I can remember/reference how the documents in a collection are structured.
