### ISSUE TITLE
how to connect mongodb

### ISSUE THREAD

**Issue by chezhe** [jedireza/hapi-mongo-models#41]
I fail to connect mongodb.
when I register plugin,there is no error,but I got
> curl: (7) Failed to connect to localhost port 8000: Connection refused

when I comment it,it's okay.

**Comment by jedireza** [comment]
Thanks for creating an issue. I'm not sure I have enough information to understand the issue. Where is the curl call coming from?

**Comment by chezhe** [comment]
localhost.I think it's my fault,not yours.
```
var hmm_plugin = {
  register: HapiMongoModels,
  options: {
      mongodb: {
        url: 'mongodb://localhost:27017/blackbox',//che:zxasqw12@
        options: {
        }
      },
      // autoIndex: false,
      // models: {
      //     User: './user',
      // }
  }
};
server.register(hmm_plugin,function(err){
  if (err) {
    console.log("Failed loading hapi-mongo-models");
    return;
  }
  console.log("Loaded hapi-mongo-models");
});
```

**Comment by chezhe** [comment]
I got it. I call server.start() while registering plugin.
Thanks for your reply.

**Comment by jedireza** [comment]
:raised_hands: glad you got it working
