### ISSUE TITLE
updateOne with positional $ operator

### ISSUE THREAD

**Issue by Mislead** [jedireza/hapi-mongo-models#43]
I have a document with the following format:

    "_id": ObjectId("234345345"),
    "name": "My name",
    "friends": [
        {
           "id" : ObjectId("2424234234234"),
           "age": 23,
           "teams" : ["team 1", "team 2", "team 3"]
        },
        {
           "id" : ObjectId("1122334455"),
           "age": 28,
           "teams" : ["team 4", "team 5", "team 6"]
        } 
    ]

I am attempting to update one object in the friends array using the "updateOne" method.

    MyModel.updateOne({_id: ObjectID(id), "friends.id": ObjectID(friendId)},{$set: {"friends.$": friendObject} }, function (err,myModel){...}).

However, nothing is being updated. Is this an issue with the UpdateOne function or am I missing something?

**Comment by Mislead** [comment]
Apologies. Issue was on my side.

**Comment by williamle8300** [comment]
@Mislead I'm trying to do the same thing. What was the mistake?
