### ISSUE TITLE
Updating an array element in a document?

### ISSUE THREAD

**Issue by williamle8300** [jedireza/hapi-mongo-models#45]
I'm trying to use the positional operator but this doesn't seem to work. Any help appreciated!

```javascript

var update = {
  $inc: {
    resellers.$.inventory: 1
  }
};

Product.findOneAndUpdate({_id : 1234,'resellers._id': 'zxcv'}, update, function (err, product) {

  if (err) {
    reply(err);
  }

  reply(product);
});

//_id: 1234,
//product: "ShamWow Blue Edition",
//resellers: [
//    {
//       _id : zxcv,
//       inventory: 23
//    },
//    {
//      _id: asdf,
//      inventory: 51
//    } ,
//    (etc)
//]
```

**Comment by williamle8300** [comment]
I figured it out. I just had to remove part of the query:

var update = {
  $inc: {
    resellers.$.inventory: 1
  }
};

Product.findOneAndUpdate({'resellers._id': 'zxcv'}, update, function (err, product) {

  if (err) {
    reply(err);
  }

  reply(product);
});

**Comment by jedireza** [comment]
Thanks for posting a follow up. :+1:

**Comment by williamle8300** [comment]
:dancer: I'm groovin' with this module. I've been using it for a year now, and it seems to be keeping up to speed with mongo pretty well. Thx for keeping this project going!

**Comment by jedireza** [comment]
That's always great to hear :blush: thanks
