### ISSUE TITLE
Boom errors

### ISSUE THREAD

**Issue by luckycadow** [jedireza/hapi-mongo-models#48]
I'm opening this to gauge support for having hapi-mongo-models return Booms instead of the raw error objects from the native driver.  I'd be happy to open a PR if this is something anyone else is interested in.  Thoughts?

**Comment by jedireza** [comment]
Thanks for opening an issue. That's an interesting idea. I'm not sure if that's the best thing to do.

From my understanding Boom was made for "HTTP-friendly error objects". And in my usage of Boom, it helps instrument error responses. Here is an example of `boom` and `hapi-mongo-models`:
https://github.com/jedireza/frame/blob/b8a49992af8d4b58cb1087b96f6e11fbfddb476b/server/api/users.js#L82-L93

You can see that if I got an `err` back from `User.findById` that I let the raw error bubble up through my handler, which will result in an HTTP 500 error. And in the case where there was no error but a document wasn't found, I use Boom to produce a HTTP 400.

Thoughts?

**Comment by luckycadow** [comment]
I noticed shortly after opening this that Hapi wraps Error objects with a Boom if it's the first argument to reply, which is what your example demonstrates.  I think that does work fine. Thanks for the response.
