### ISSUE TITLE
Query ISODate

### ISSUE THREAD

**Issue by jgauna** [jedireza/hapi-mongo-models#55]
I have a document in my collection 

```"created_date" : ISODate("2016-05-20T04:44:08.492Z")```

 and when I query it from Robomongo using

 ```find({"created_date": new Date("2016-05-20T04:44:08.492Z")})``` it works ok.

When I do it from my hapi model I get zero results:

```
  filter.created_date = new Date("2016-05-20T04:44:08.492Z");
  
  this.find(filter, function(err, res) {
    console.log("res", res); // Empty Array here!
  });
```

Am I missing something or is it a bug? Thanks!

**Comment by jgauna** [comment]
Never mind. My mistake. Thanks!

**Comment by jedireza** [comment]
Glad you got it worked out. What was the solution? What was the mistake?

**Comment by jgauna** [comment]
I thought somewhere it was converting the date object into a string but the mistake was that I called another model :-1: 

Here's the final code if anyone needs this:

```
filter.created_date = {
  '$gte': new Date(startDate),
  '$lte': new Date(endDate)
};
```
Where ```startDate``` and ```endDate``` is something like ```02/12/2016```

Thanks!
