### ISSUE TITLE
why is mongodb module on devDependencies

### ISSUE THREAD

**Issue by genediazjr** [jedireza/hapi-mongo-models#56]
I would just like to know. Thanks!
https://github.com/jedireza/hapi-mongo-models/blob/master/package.json#L36

**Comment by jedireza** [comment]
Thanks for opening an issue. `mongodb` is in `devDependencies` so it's installed during testing, but not in production. `mongodb` it's also in `peerDependencies` so the consumer app knows they need to install it.
