### ISSUE TITLE
QUESTION: Does this plug-in support associations?

### ISSUE THREAD

**Issue by bryandent** [jedireza/hapi-mongo-models#61]
Hi, I'm new to HAPI and need some notion of models in our new project.  We come from using SailsJS which offers some notion of Associations with the use of Waterline.  Does your plug-in offer us the ability to have associations and specifically the ability to populate an associated child model?

**Comment by jedireza** [comment]
Thanks for opening an issue.

No, this module doesn't support automatic associations or hydration. When I want to populate/hydrate some association, I instrument them on my models.

For example, here I define a `hydrate` method on a model:
 - https://github.com/jedireza/frame/blob/984e5a8ac72d163a0dfc404f392b447878827d24/server/models/user.js#L30-L68 

And elsewhere, I call `hydrate` on an instance it to populate it:

 - https://github.com/jedireza/frame/blob/984e5a8ac72d163a0dfc404f392b447878827d24/server/auth.js#L37

**Comment by bryandent** [comment]
@jedireza I'll check this out.  Thanks so much!
