### ISSUE TITLE
server.start() to include Mongo models?

### ISSUE THREAD

**Issue by Miscellaneous** [jedireza/hapi-mongo-models#63]
Would something like this be possible to call from server.start()?

```
const server = new Hapi.Server();
...
server.start( function() {
    const Game = server.plugins['hapi-mongo-models'].Game;

    Game.find( {}, function( err, result ) {
        console.log( result );
    });
});
```

Error:
.../node_modules/hapi-mongo-models/lib/base-model.js:259
const collection = BaseModel.db.collection(this._collection);
                              ^

TypeError: Cannot read property 'collection' of undefined

**Comment by Miscellaneous** [comment]
using setTimeout() for the desired result
```
const server = new Hapi.Server();
...
server.start( function() {
    const Game = server.plugins['hapi-mongo-models'].Game;

    setTimeout( function() {
        Game.find( {}, function( err, result ) {
            console.log( result );
        });
    }, 3000 );
});
```

**Comment by jedireza** [comment]
Thanks for opening an issue. Using a `setTimeout` isn't a great solution. You may be interested in `server.initialize()`. See: http://hapijs.com/api#serverinitializecallback

**Comment by Miscellaneous** [comment]
I already tried server.initialize(), it resulted in same error.
