### ISSUE TITLE
v6.0.0 release notes

### ISSUE THREAD

**Issue by jedireza** [jedireza/hapi-mongo-models#66]
## General

We've split the `BaseModel` out into it's own repo, which makes it a more general tool outside of hapi applications. We're now exclusively using es6 classes instead of using the `ampersand-class-extend` hack.
## Breaking changes
- `BaseModel` has moved into it's own package [`mongo-models`](https://github.com/jedireza/mongo-models/). It is also referred to as `MongoModels` instead of `BaseModel`.
- `mongo-models` is a new `peerDepdendency` you'll need to include in your application's `package.json`.
- `BaseModel.extend(...)` is gone. Simply extend with es6 `class Customer extends MongoModels {}`
- The `_collection` property has been renamed to `collection`. Ex: `Customer._collection = 'customers';` will now be `Customer.collection = 'customers';`.
- `BaseModel.connect(options, callback)` arguments have changed to `MongoModels.connect(uri, options, callback)`
- The options passed to the plugin have a minor change. The `url` property is now `uri`.

**Comment by svnlto** [comment]
🎉
