### ISSUE TITLE
using aggregate function 

### ISSUE THREAD

**Issue by shreyapandit** [jedireza/hapi-mongo-models#68]
Hey @jedireza I am unable to relate the the example in #15 (As you mentioned in #21 ) with how to use an aggregate method for models. Our app has custom models extended from BaseModel itself, but there seems to be no aggregate function within it. Help is much appreciated, thank you 🙏

**Comment by jedireza** [comment]
Thanks for creating an issue.

As of v6.x ([release notes](https://github.com/jedireza/hapi-mongo-models/issues/66)), we've abstracted the core functionality into it's own library called [`mongo-models`](https://github.com/jedireza/mongo-models/), which we depend on with this hapi plugin.

Less than a month ago we updated `mongo-models` to expose an `aggregate` method. So as long as you're using the latest version of this plugin, your models should have an `aggregate` method on them. Docs link: https://github.com/jedireza/mongo-models/blob/master/API.md#aggregatepipeline-options-callback

Then you can:

```js
MyModel.aggregate(pipeline, (err, results) => {

    // ...
})
```

**Comment by shreyapandit** [comment]
Amazing, thanks for the quick turnaround on this @jedireza . I switched to mongo-models and it works perfectly now! Cheers 👍 😄
