### ISSUE TITLE
Not expected results in v6.0.0 responses

### ISSUE THREAD

**Issue by jgauna** [jedireza/hapi-mongo-models#69]
So far, plugin is already registered:

```
// AdminModel.js

var Admin = require('hapi-mongo-models').MongoModels;

Admin.indexes = [{
  key: {
    username: 1
  },
  unique: true
}, {
  key: {
    email: 1
  },
  unique: true
}];

Admin.collection = 'admins';

Admin.schema = validation;

Admin.findByUsername = function(username, callback) {
  var filter = {};
  this.find(filter, callback);
};
```

```
// other.js

var admin = require('AdminModel');

admin.findByUsername('someUser', function(err, res) {
  console.log(res);
});
```

And the result is:

```
MongoModels {
  _id: 58490c05aa6bbf587f55951d,
  username: 'someUser',
  password: '123456',
  user_type: 'admin' }
```

I have updated from v5.0.1 to v6.0.0 and fixed the breaking changes but with no luck. Pretty sure that i'm doing something wrong but can't figure out what it is.

**Comment by jedireza** [comment]
Thanks for opening an issue. Have you read the breaking changes issue? https://github.com/jedireza/hapi-mongo-models/issues/66

**Comment by jgauna** [comment]
Yes but no luck. Is there any chance to use es5 insted of es6 classes for creating the models ?

**Comment by jedireza** [comment]
Nope. We require node 6+ which supports es6 classes.
