### ISSUE TITLE
MongoDB custom logger

### ISSUE THREAD

**Issue by trainerbill** [jedireza/hapi-mongo-models#71]
Can a mongodb custom logger be implemented to switch the Mongo logger to server.log?  Also would need a logLevel option.

http://mongodb.github.io/node-mongodb-native/2.0/tutorials/logging/

goal would be to provide the option logLevel: "debug" and then mongodb would use server.log to log to the console in mongodb debug mode.

new to hapi so if there is a better way to accomplish this let me know.

**Comment by jedireza** [comment]
This sounds like a cool idea. I'm short on time to drive this feature. It should be possible though. If anyone has time, help is much appreciated. Let us know what you find.
