### ISSUE TITLE
Hapi v17 support

### ISSUE THREAD

**Issue by BorntraegerMarc** [jedireza/hapi-mongo-models#73]
Will this plugin be supported in hapi v17? It's listed as an official plugin in the hapi website.

**Comment by jedireza** [comment]
> Will this plugin be supported in hapi v17?

I plan on it.

> It's listed as an official plugin in the hapi website.

The plugins listed on https://hapijs.com/plugins don't designate what I'd consider "official". I'd consider plugins in the https://github.com/hapijs/ org as the official ones.
