### ISSUE TITLE
Support for ssh tunnel ?

### ISSUE THREAD

**Issue by jgauna** [jedireza/hapi-mongo-models#76]
Hello,

has this plugin support for mongodb ssh tunnel ? I can't find a way to connect

**Comment by jedireza** [comment]
> mongodb ssh tunnel

I'm unfamiliar with ssh tunnels and mongodb personally. If it's like this: https://serverfault.com/questions/597765/how-to-connect-to-mongodb-server-via-ssh-tunnel

Then your local machine would simply be proxying and you'd use your local server (`127.0.0.1` or `localhost`) as the server address.

**Comment by jgauna** [comment]
That's correct but it would be neccesary to access the mongo's connect function to call it after we register the plugin using https://github.com/agebrock/tunnel-ssh

```
   var tunnel = require('tunnel-ssh');
    var tnl = tunnel(mongoTunnelConfig, function(error, tnl){
              // Call mongo plugin connect method
      });
```

Is it possible to acomplish that?

**Comment by jedireza** [comment]
I see. In that case I'd just look at the source of `hapi-mongo-models` and create a plugin just for your app. This seems like an edge case.

**Comment by jgauna** [comment]
mmh i don't think it's an edge case because it's a common thing ssh tunnel with mongo (you can avoid listen external connections using ssh and mongo remains safe). Anyway, it would be nice to pass an extra parameter like ```ssh:true``` in the config object and your plugin evals that and internally uses ssh-tunnel to perform the connection. Just a thought

**Comment by jedireza** [comment]
> Anyway, it would be nice to pass an extra parameter like ssh:true in the config object and your plugin evals that and internally uses ssh-tunnel to perform the connection.

I don't think this is a good fit for this module. Thanks for mentioning this  though.

The source of this plugin is really simple. The README talks about special cases:

> Note: This plugin is designed for basic use-cases. If you find yourself needing more, consider using the source as inspiration and create a custom plugin for your app.

**Comment by jgauna** [comment]
Thanks @jedireza for clarify
