### ISSUE TITLE
models "path/to/customer" might be off?

### ISSUE THREAD

**Issue by Miscellaneous** [jedireza/hapi-mongo-models#77]
Migrating from Hapi 14 to 17.6, any idea why below isn't working?

Doesn't work:
        models: [
            './models/user'
        ],

Works:
        models: [
            '/home/Hapi17/models/user'
        ],

**Comment by Miscellaneous** [comment]
This seems to be a NodeJS or HapiJS thingie

**Comment by jedireza** [comment]
Please add more detail for anyone else who may come across this in the future.
