### ISSUE TITLE
Plugin example for 7.x.x?

### ISSUE THREAD

**Issue by Miscellaneous** [jedireza/hapi-mongo-models#79]
I can find plugin example for hapi-mongo-models 6.x (via source history), but can't seems to find anything for 7, did you neglect this?

**Comment by jedireza** [comment]
Yeah having an example in the readme would be good. Please consider creating a pull request.

In general though instead of getting to the model singleton via:

```
const Customer = request.server.plugins['hapi-mongo-models'].Customer;
```

I think it's better to just require them directly. This makes testing easier also:

```
const Customer = require('./path/to/models/customer.');
```

**Comment by Miscellaneous** [comment]
Yea, agree

**Comment by Miscellaneous** [comment]
// app.js

'use strict';

const Hapi = require('hapi');
const HapiMongoModels = require('hapi-mongo-models');

const mongodbPlugin = {
    plugin: HapiMongoModels,
    options: {
        mongodbdb: {
            connection: {
                uri: 'mongodb://localhost:27017/',
                db: 'hapi-mongo-models-test'
            },
            options: {
                useNewUrlParser: true
            }
        },
        models: [
            Path.resolve(__dirname, 'models/customer'),
            Path.resolve(__dirname, 'models/stock')
        ],
        autoIndex: false
    }
};

const startServer = async function()
{
    try {
        await server.register( mongodbPlugin );
    }
    catch( err ){ return console.log( err ) }


    try {
        await server.start();
    }
    catch (err) {
        console.log(err);
        process.exit(1);
    }

    const startRouters = async function()
    {
        try {
            await server.register({
                plugin: require('./plugins/customer'),
                options: {
                    mongodb: 'mongodb://localhost:27017/',
                    autoIndex: false,
                    models: {
                        Customer: './models/customer'
                    }
                }
            });
        }
        catch( err ){ return console.log( err ) }

        try {
            await server.register({
                plugin: require('./plugins/stock'),
                options: {
                    mongodb: 'mongodb://localhost:27017/',
                    autoIndex: false,
                    models: {
                        Stock: './models/stock'
                    }
                }
            });
        }
        catch( err ){ return console.log( error: err ) }
    };

    startRouters();
}

startServer();

// plugins/customer.js
'use strict';

const Joi = require('joi');
const Stock = require('../models/stock'); //Optional if needing access to other models

exports.plugin = {
    name: 'customer',
    register:( server, options ) => {

        server.route({
            method: 'GET',
            path: '/customer',
            options: { auth: false },
            handler: async function( request, h )
            {
                var result = null;
                try{
                     result = await Customer.find( {}, { projection: { _id:0 }});
                }
                catch( err ){ return console.log( err )}

                return result;
            }
        });
    }
};



// plugins/stock.js
'use strict';

const Joi = require('joi');
const Customer = require('../models/customer'); //Optional if needing access to other models

exports.plugin = {
    name: 'ability',
    register:( server, options ) => {

        server.route({
            method: 'GET',
            path: '/stock',
            options: { auth: false },
            handler: async function( request, h )
            {
                var result = null;
                try{
                     result = await Stock.find( {}, { projection: { _id:0 }});
                }
                catch( err ){ return console.log( err )}

                return result;
            }
        });
    }
};
