### ISSUE TITLE
If connection.db is optional, why is there an assertion error if it isn't provided?

### ISSUE THREAD

**Issue by nickrobillard** [jedireza/hapi-mongo-models#84]
According to https://github.com/jedireza/mongo-models/issues/39, `connection.db` is optional. I have observed that it **is** indeed optional and works as expected without `db` when `uri` contains the db name.

However, **hapi-mongo-models** still contains this line which throws an error if `connection.db` is not provided:
```
Hoek.assert(options.mongodb.connection.db, 'options.mongodb.connection.db is required');
```

Which throws this error if `db` is undefined or null:
```
Catch error on server start. Process will terminate now. { AssertionError [ERR_ASSERTION]: options.mongodb.connection.db is required
    at new AssertionError (internal/assert.js:269:11)
```

I see that `options.mongodb.connection` is just passed through to **mongo-models** which means that db should also be considered optional in **hapi-mongo-models**. Am I missing something? Can we just remove the above assertion in **hapi-mongo-models**?

**Comment by jedireza** [comment]
I’m time poor at the moment. We need to check how far apart the versions are and if we can make the switch. Feel free to submit a PR and I will review.
